services:
  grubpeek:
    image: ghcr.io/dick86114/grubpeek:latest
    container_name: grubpeek
    restart: unless-stopped
    ports:
      - "2618:2618"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/grubpeek.db
      - MENU_DIR=/app/data/menu
      - ADMIN_PASSWORD=admin888  # 设置初始管理员密码，仅在首次运行时生效
      - TZ=Asia/Shanghai
